### ISSUE TITLE
ohm.js grammar

### ISSUE THREAD

**Issue by cdaringe** [opendevise/asciidoc-parsing-lab#33]
I didn't realize this repo existed before i started!

I've been developing (and will continue to develop) a pseudo grammar, which I hope to target ~98-99% core asciidoc parsing/printing here: https://github.com/cdaringe/asciidoc-ts/blob/2ed1eb4af6fb2c26f8906d84748bdd4a389a0a9a/src/mod.ts#L10-L217

still very much not done. just fyi!

**Comment by cdaringe** [comment]
it's so rough right now that I was hesitant sharing 😄  🤷

**Comment by mojavelinux** [comment]
That's cool to hear!

We'd be thrilled if you shared your progress in the project chat at https://chat.asciidoc.org.
